spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

server.port=${PORT:8080}

api.security.token.secret=${JWT_SECRET:12345678}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true