package med.voll.api.domain.medico;

public enum Especialidade {

    ORTOPEDIA,
    CARDIOLOGIA,
    GINECOLOGIA,
    DERMATOLOGIA,
    PEDIATRIA,
    NEUROLOGIA,
    PSIQUIATRIA,
    OFTALMOLOGIA,
    UROLOGIA,
    ENDOCRINOLOGIA,
    ONCOLOGIA,
    REUMATOLOGIA,
    INFECTOLOGIA,
    NUTROLOGIA,
    OTORRINOLARINGOLOGIA,
    RADIOLOGIA,
    ANESTESIOLOGIA,
}
